version: '3.8'
services:
  # Gateway
  gateway:
    build: ./gateway
    ports: ["3000:3000"]
    depends_on: [auth-service]

  # Microservices
  auth-service:
    build: ./services/auth-service
    environment:
      - JWT_SECRET=super-secret
      - DATABASE_URL=mongodb://mongo:27017/matchai
    depends_on: [mongo]

  # Database
  mongo:
    image: mongo:6
    ports: ["27017:27017"]
    volumes: ["mongo_data:/data/db"]

  redis:
    image: redis:alpine
    ports: ["6379:6379"]

  # Frontends
  web-mobile:
    build: ./apps/web-mobile
    ports: ["3001:3000"]

  admin-dashboard:
    build: ./apps/admin-dashboard
    ports: ["3002:3000"]

  # Nginx Proxy
  nginx:
    image: nginx:alpine
    ports: ["80:80"]
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on: 
      - gateway
      - web-mobile
      - admin-dashboard

volumes:
  mongo_data: