openapi: 3.0.1
info:
  title: MatchAI API
  version: 1.0.0
paths:
  /api/auth/login:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email: { type: string }
                password: { type: string }
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  token: { type: string }